#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

# Check if exactly one argument is passed
if [ "$#" -ne 1 ]; then
	echo "Usage: 5-mysql_backup <password>"
	exit 1
fi

MYSQL_USER="root"
DATABASES=$(mysql -u $MYSQL_USER -p"$1" -e "SHOW DATABASES;" | grep -Ev '^(Database|information_schema|mysql|performance_schema|sys)')
DUMP_FILE="backup.sql"
DATE=$(date +%d-%m-%Y)
ARCHIVE_FILE="${DATE}.tar.gz"

mysqldump -u $MYSQL_USER -p"$1" $DATABASES > $DUMP_FILE

# Check if the dump was successfully created
if [ $? -eq 0 ]; then
	tar -czvf $ARCHIVE_FILE $DUMP_FILE
	exit 0
fi

exit 1

