#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.


DUMP_FILE="backup.sql"
DATE=$(date +%d-%m-%Y)
ARCHIVE_FILE="${DATE}.tar.gz"

mysqldump -uroot -p"$1" -A > $DUMP_FILE

tar -czvf $ARCHIVE_FILE $DUMP_FILE


