#!/usr/bin/env bash
# This ia a script that displays numbers from 1 to 100
# It displays FizzBuzz when a number is a multiple of
# 3 and 5, displays Fizz when the number is multiple
# of 3 and displays Buzz when the number is a multiple
# of 5. Otherwise, it displays the number all n a 
# list format.

i=1

while ((i<101))
do
	if [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ]
	then
		echo "Fizzbuzz"
	elif [ $((i%3)) == 0 ]
	then 
		echo "Fizz"
	elif [ $((i%5)) == 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((++i))
done

