#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

SCHOOL="Best School"; # local variable to hold text
i=0; # intializing counter

while [ $i -lt 10 ]
do
	echo "$SCHOOL"
	i=$((i+1))

	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
done
