#!/usr/bin/env bash
# This script loops from 1 to 10 and displays bad luck
# for the 4th iteration, good luck for the 8th and Best School for others

str_4="bad luck from China"
str_9="bad luck from Japan"
str_17="bad luck from Italy"
i=1

while [ $i -lt 21 ]
do
	case $i in
		4)
			echo "$i" & echo "$str_4" & i=$((i+1))
			;;
		9)
			echo "$i" & echo "$str_9" & i=$((i+1))
			;;
		17)
			echo "$i" & echo "$str_17" & i=$((i+1))
			;;
		*)
			echo "$i" & i=$((i+1))
			;;
	esac
done
