#!/usr/bin/env bash
# This script loops from 1 to 10 and displays bad luck
# for the 4th iteration, good luck for the 8th and Best School for others

str_4="bad luck from China"
str_9="bad luck from Japan"
str_17="bad luck from Italy"
i=1

while [ $i -lt 21 ]
do
	echo "$i"
	case $i in
		4)
			echo "$str_4"
			;;
		9)
			echo "$str_9"
			;;
		17)
			echo "$str_17"
			;;
	esac
	i=$((i+1))
done
